"""The committed gemini-extension.json and llms.txt must match their derivation.

Both files are generated by scripts/derive_artifacts.py from server.json,
pyproject.toml and llms-full.txt. They stay committed (Gemini installs the
extension from the repo; llms.txt is fetched from main), so this test is the
guard that a hand-edit — or a change to a source file that was not regenerated —
does not silently drift.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
_SCRIPT = ROOT / "scripts" / "derive_artifacts.py"

_spec = importlib.util.spec_from_file_location("derive_artifacts", _SCRIPT)
assert _spec and _spec.loader
derive_artifacts = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(derive_artifacts)


@pytest.mark.parametrize(
    ("filename", "deriver"),
    [
        ("gemini-extension.json", derive_artifacts.derive_gemini),
        ("llms.txt", derive_artifacts.derive_llms_txt),
    ],
)
def test_committed_file_matches_derivation(filename: str, deriver) -> None:
    committed = (ROOT / filename).read_text(encoding="utf-8")
    assert committed == deriver(), (
        f"{filename} is out of date — run `python scripts/derive_artifacts.py`"
    )
